### ISSUE TITLE
Check if Preservica security tags are case sensitive

### ISSUE THREAD

**Issue by pmasereeuw** [noord-hollandsarchief/preingest#101]
E.g., are TAG_xxx and ROLE_xxx equivalent with TAG_xXx and ROLE_xXx? This should be tested in Preservica.

**Comment by pmasereeuw** [comment]
Tot mijn verrassing moet ik vaststellen dat de tags case sensitive lijken te zijn. Dit is wat ik heb gedaan:

1. Ik heb in de metadata van mijn testset voor het werken met de securitytags in de ToPX-metadata de waarde van `<omschrijvingBeperkingen>`aangepast door ze op een plaats om  te zetten naar uppercase en elders naar lowercase.
2. Ik heb de oorspronkelijke bestanden in de Preservica-root-folder /DEVTEAMNHA_4 verwijderd (met behulp van twee gebruikersnamen).
3. Helaas bleek dat de conversie naar XIP de namen normaliseert, maar bij het ingevoerde Toegang_intern_test (oorspronkelijk Toegang_Intern_Test) bleek het laatste stukje (dus _test) wel letterlijk overgenomen. De test kon dus doorgaan. De naam van de tag in Preservica is Tag_DEVTEAMNHA_Intern_Test.
4. Bij het doen van ingest kreeg ik foutmeldingen: 
![Selection_001](https://user-images.githubusercontent.com/6839743/111616958-cefd5680-87e2-11eb-9cc2-f46959bde651.png)
4. Met het oorspronkelijke SIP-bestand, dus met de naam eindigend op _Test ging de ingest probleemloos.

In de preingest-fase moeten we dus zorgvuldig zijn met:
- consequente spelling van de naam van de zorgdrager (die deel wordt van de tag)
- controleren van het variabele deel in Toegang_Intern_XXX

@avbentem Misschien is het goed als de conversie het variabele deel omzet naar hoofd- of juist kleine letters? Dan ligt onze zorg alleen maar bij het juist invoeren van tags in Preservica.

Naar de hoofdlettergevoeligheid van rollen heb ik niet gekeken, omdat je die, eenmaal aangemaakt, in Preservica alleen maar kunt aanwijzen, niet intikken.

**Comment by avbentem** [comment]
For now, given existing security tags in the test environment, this will be mapped to use `Tag_<owner>_Publiek`, `Tag_<owner>_Intern_some_code` and all. May still change in the near future.
