### ISSUE TITLE
Doing a pre-wash to fix small defects in sidecar metadata files?

### ISSUE THREAD

**Issue by pmasereeuw** [noord-hollandsarchief/preingest#102]
Ingest material may suffer from certain flaws in the metadata. We already encountered the word "bytes" in the `<omvang>` fields that only allows digits. Many flaws are expected to be automatically fixable. This might be done in an XSLT script inside XSLWeb.

The options are:
1. Turn the current ToPX-to-XIP transform into a pipeline with an optional, _zorgdrager_-specific, first step, OR
2. Do an extra step preceding ToPX validation

In the first option, validation errors will remain which may or may not be a good thing. Awareness of flaws does not seem bad to me.
In the second option, all predictable, zorgdrager-specific flaws will be removed, never to be seen again.

Let's discuss this.

**Comment by avbentem** [comment]
- For future automated handling of incoming files, the validation should not raise errors if we fixed errors or enriched data using some per-project transformation. So, per-project transformations should happen before validation. (To see the original errors during testing, we could disable/remove the extra transformation.)
- xslweb expects XSLT files in a certain folder (and it will monitor that folder for changes). For the regular transformations this folder is already mapped to a folder in the Docker image. We'll create a subfolder in that folder and map it to some volume outside of the docker container. This needs an additional environment setting.
- The settings JSON will be extended with something to indicate the name of the selected XSLT file, if any.
- As running before the validation means that all of this cannot run as part of `TransformationHandler`, we'll need an additional handler (including API and scheduler, and some means to get the list of existing XSLT files in the new folder).
- Excel-reporting should include the name of the extra transformation XSLT, if any.

**Comment by pmasereeuw** [comment]
The XSLWeb webapp transform has a new transformation: **prewash**.

It works in the same way as the already existing topx2xip transformation, but the URL starts with `/transform/prewash/` instead of `/transform/topx2xip`. So what follows is a lot of text (TL;DR), but it boils down to: _do the same as with topx2xip_.

As with topx2xip, the remainder of the url should consist of the (encoded) path to the metadata file, so e.g.

[http://localhost:8888/transform/prewash/0ee4629b-3394-6986-b859-430c0256ecd1/Provincie%20Noord%20Holland/Provincie%20Noord%20Holland.metadata](http://localhost:8888/transform/prewash/0ee4629b-3394-6986-b859-430c0256ecd1/Provincie%20Noord%20Holland/Provincie%20Noord%20Holland.metadata)

The prewash stylesheets will be located in a subdirectory inside the XSLWeb docker. That directory will be mounted outside the docker container, for instance with the following setting in `docker-compose.yml`: **`/path/to/prewash/:/nha/xslweb/home/webapps/transform/xsl/prewash/`**

The basename of the required prewash stylesheet (without path and without .xslt extension) should be passed (encoded) via the request parameter `prewash`. This setting will need to be part of the settings object in `SettingsHandler.json` file. If the same logic as with topx2xip is followed, it will be sufficient if all values from the settings object are passed as request parameters. In the future, both topx2xip and prewash may require more parameters.

As with topx2xip, the result of the request will be an XML response with the transformed file. That file should be saved to disk and replace the original file. If there is an error, the HTTP status code will be 400 (and the response will be an XML structure with a description, as in topx2xip).

The attached stylesheet (please remove the `.txt` extension required by Github) can be placed inside the mounted prewash stylesheets folder for testing. The testing URL could be something like

[http://localhost:8888/transform/prewash/0ee4629b-3394-6986-b859-430c0256ecd1/Provincie%20Noord%20Holland/Provincie%20Noord%20Holland.metadata?prewash=sample-prewash-stylesheet](http://localhost:8888/transform/prewash/0ee4629b-3394-6986-b859-430c0256ecd1/Provincie%20Noord%20Holland/Provincie%20Noord%20Holland.metadata?prewash=sample-prewash-stylesheet)

The effect will be that some extra text is added to all `<identificatiekenmerk>` elements. If that is the case, it works.

[sample-prewash-stylesheet.xslt.txt](https://github.com/noord-hollandsarchief/preingest/files/6248754/sample-prewash-stylesheet.xslt.txt)

**Comment by avbentem** [comment]
@pmasereeuw:

> the stylesheet that also serves as the default stylesheet when the request dispatcher does not find a specific one

Can we fail rather then silently ignore in this case?

> That directory will be mounted outside the docker container

Can you please add an environment setting for that in `docker-compose.yml` and `docker-compose.dev.yml`? (Aside, I've reverted https://github.com/noord-hollandsarchief/preingest/commit/a00a97520a240eed2b492d8307b5723792f53b08 and undid the change to `.gitignore` from https://github.com/noord-hollandsarchief/preingest/commit/39d45ad74d5c88bd9d19ed4a615f044e03be6c78; that file is very much part of the documentation.)

@whyyellow:

I've added a setting `prewash` and an action `PrewashHandler` ("Voorbewerking") to the frontend. (Once an API endpoint is available to get a list of files in the prewash folder, the text input will be replaced with a dropdown that gets the available scripts from the server. 

![frontend](https://user-images.githubusercontent.com/1497002/113668510-a3b7aa00-96b2-11eb-9a89-7589d11884ed.png)

Along with what Pieter described above, we need:

- the settings API to accept the optional `prewash`
- the scheduler to accept `PrewashHandler`
- a new handler for that; just like the `ChecksumHandler` this should fetch the setting for `prewash`
- an API endpoint to get a list of files in the folder that holds the pre-wash XSLT file(s)

**Comment by pmasereeuw** [comment]
- De prewash faalt nu met een 400-status als een stylesheet niet kan worden geladen
- De folder met de prewash-stylesheets moet nu geconfigureerd met een variabele `XSLWEBPREWASHFOLDER` (in .env)
- Een basisversie van deze folder staat nu in git onder de toplevel folder `nhapreingest`
- Het convience-stylesheet met de identity transform heet nu `_prewash-identity-transform.xslt`

**Comment by WhyYellow** [comment]
Committed in [https://github.com/noord-hollandsarchief/preingest/commit/d6f142512e73e76f5297e625ba4414a5bfe7eb84](url)

- Settings contains property Prewash
- PrewashHandler is added with same functionality as TransformationHandler
- There is an call available for retrieving a list of files (/api/Output/prewashlist)
- Worker service is updated with prewash command
- In docker-compose file settings for webapi are updated

**Comment by pmasereeuw** [comment]
@avbentem zeg in Teams:
_Wat geeft de pre-wash trouwens door als er iets fout gaat? Als je een foute XSLT hebt, dan zie je in de Docker logs wel de foutmelding, maar de API zegt dat-ie een 500 gekregen heeft. Zou mooi zijn als de API de XSLWeb foutmelding kan laten zien:

`"The remote server returned an error: (500) .", " at System.Net.HttpWebRequest.GetResponse()\n at System.Net.WebClient.GetWebResponse(WebRequest request)\n at System.Net.WebClient.DownloadBits(WebRequest request, Stream writeStream)\n at System.Net.WebClient.UploadBits(WebRequest request, Stream readStream, Byte[] buffer, Int32 chunkSize, Byte[] header, Byte[] footer)\n at System.Net.WebClient.UploadDataInternal(Uri address, String method, Byte[] data, WebRequest& request)\n at System.Net.WebClient.UploadString(Uri address, String method, String data)\n at Noord.HollandsArchief.Pre.Ingest.WebApi.Handlers.PrewashHandler.Execute() in /src/Noord.HollandsArchief.Pre.Ingest.WebApi/Handlers/PrewashHandler.cs:line 50" ]`
_

**Comment by pmasereeuw** [comment]
XSLWeb kan twee fouten geven: een compiletime-fout (stylesheet-syntax is niet goed) of een runtime-fout.

**Runtime-fout (zelf ff gegenereerd met de error() functie):**

```
HTTP/1.1 400 
Content-Type: application/xml
..
<?xml version="1.0" encoding="UTF-8"?><message xmlns:nha="http://noord-hollandsarchief.nl/namespaces/1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema" error-code="foutje-bedankt" module="file:///nha/xslweb/home/webapps/transform/xsl/prewash/klad.xslt" line-number="18">Er is iets helemaal niet zo goed gegaan jongens</message>
```

**Compiletime-fout:**
```
HTTP/1.1 400 
Content-Type: application/xml
..
<?xml version="1.0" encoding="UTF-8"?><message xmlns:xs="http://www.w3.org/2001/XMLSchema" error-code="nha:invalide-prewash-stylesheet">Could not open or parse prewash stylesheet "prewash/klad.xslt"</message>

```
M.a.w., wrsch. moet er iets anders teruggegeven worden dan een error-message in XML-vorm. Maar wat (voor json)?

N.B. Dit speelt op meer plaatsen waar XSLWeb een rol speelt.

**Comment by pmasereeuw** [comment]
@avbentem @WhyYellow Wai zegt dat hij nu al een XML-response kan verwerken. Oplossing ligt dus bij hem, storm in glas water lijkt het.

**Comment by avbentem** [comment]
@pmasereeuw @WhyYellow Als XSLweb inderdaad geen 500 stuurt (is bij twijfel nog wel te testen met een directe aanroep, zonder frontend, `workservice` en de `preingest` API?), dan zit het volgende ergens tussen de workservice en de API? (De frontend praat alleen met de API van `preingest`.)

> The remote server returned an error: (500)

**Comment by pmasereeuw** [comment]
@avbentem misschien kun je zeggen welk stylesheet het probleem veroorzaakt, dan kan ik kijken of ik het kan reproduceren.

**Comment by avbentem** [comment]
@pmasereeuw, een willekeurige fout is genoeg. Bijvoorbeeld `xx` tikken in `<xsl:xxvalue-of ...>`, niet-bestaande functienaam of verkeerd aantal parameters in `select="replace(., '^\D*(\d+)\D*$', '$1')"`, of een niet-bestaande bestandsnaam in `<xsl:import ...>`. Laat allemaal bovengenoemde foutmelding zien.

**Comment by avbentem** [comment]
Just to be sure: for such errors the result still needs to be `failed` (not just `error`), just like it is right now. It's just that the original error is lost, somewhere.

![failed action](https://user-images.githubusercontent.com/1497002/114901523-2cea8180-9e15-11eb-8ade-68ea32bbf8b8.png)

**Comment by avbentem** [comment]
Moved the error handling into #106.
