### ISSUE TITLE
omschrijvingBeperkingen, openbaarheid

### ISSUE THREAD

**Issue by pmasereeuw** [noord-hollandsarchief/preingest#104]
In ToPx is omschrijvingBeperkingen niet verplicht, omdat het parent-element openbaarheid een cardinaliteit van 0-unbounded heeft. In Schematron controleren we echter of er precies één element omschrijvingBeperkingen is.

@avbentem schrijft:
`<q>`
Maar niet in TMLO, toch? Dat was toch de reden dat we besloten om het botweg niet meer toe te staan (in plaats van te controleren of de waarde op bestandsniveau overeenkomt met de parent, omdat we het niet via XIPv4 in Preservica kunnen krijgen)?
`</q>`

Ik heb nooit ergens een schema van TMLO kunnen vinden. Misschien is het alleen maar een beschrijving en is ToPX het schema?

Hoe dan ook, volgens [die beschrijving](https://www.nationaalarchief.nl/sites/default/files/field-file/metadatamodel_edepot_v1.1.pdf) "omschrijving beperkingen" is verplicht, maar het bovenliggende veld, openbaarheid, heeft als verplichtheidskenmerk _Vivt_ - Verplicht indien van toepassing. Dus ja, dat klinkt als "niet helemaal verplicht".

Ik heb niet in de beschrijving van TMLO kunnen vaststellen welke rol het aggregatieniveau speelt. M.a.w. geldt voor "stuk" (= bestand?) hetzelfde als voor hogere niveaus?

Hoe dan ook, het XIP-formaat van Preservica laat geen `<SecurityTag>` toe op bestandsniveau. OPEX mogelijk wel. Ook het objectmodel van Preservica lijkt het op het niveau van Content Object toe te staan.

**Comment by pmasereeuw** [comment]
Ik heb ook nagegaan wat het gedrag van de SIP Creator is wanneer je in de GUI bij de settings openbaar, niet-openbaar of geen opgeeft. Het effect is dat deze waarde wordt ingevuld op het moment dat in de XIP-versie van de sidecar geen element `<SecurityTag>` aanwezig is. Indien `<SecurityTag>` wèl aanwezig is, maar leeg, vult de SIP Creator de waarde **open** in, ongeacht wat er in SettingsHandler.json staat.

Het is ook niet zo dat het bovenliggende niveau (dus de waarde van SecurityTag in de sidecar in de bovenliggende folder) wordt gebruikt. Ik heb dit nagegaan door met de hand van laag naar hoog de XIP-versie van sidecar-files bij te editen.

Ook is het niet zo dat Preservica standaardwaardes invult. Ik heb het SettingsHandler.json met de hand aangepast en er een gekke waarde ingezet, en die gekke waarde komt terug in het resultaat.

**Comment by pmasereeuw** [comment]
@avbentem  gezien het gedrag van de SIP Creator bij een lege waarde van `<SecurityTag>`, stel ik voor dat we zorgen dat de conversie `<SecurityTag>` weg laat als `<omschrijvingBeperkingen>` leeg of niet aanwezig is. Dat laatste geeft wel een Schematron-waarschuwing, maar die zou je kunnen negeren. Je wilt natuurlijk niet dat iets onbedoeld openbaar wordt.

**Comment by pmasereeuw** [comment]
In overleg met Arjan inderdaad gezorgd dat de ToPX2XIP-conversie geen `<SecurityTag>` in de XIP plaatst als `<omschrijvingBeperkingen>` ontbreekt of leeg is (na trimmen van spaties). Dit om te voorkomen dat er archiefmateriaal onbedoeld openbaar toegankelijk wordt.

**Comment by pmasereeuw** [comment]
Vanaf 30 maart 2021 zijn dit de regels waarmee topx2xip de `<SecurityTag>` bepaalt:

- Indien er in de settings de waarde `open` of `closed` is  ingevuld (in de GUI: "Forceer ..."), dan geldt die waarde, ongeacht wat er in ToPX staat
- Anders, als er zich in ToPX een element `<omschrijvingBeperkingen>` bevindt, en de tekst daarin is niet leeg, dan wordt die waarde zo mogelijk  omgezet naar een `<SecurityTag>` (met daarin de naam van de zorgdrager). Als het formaat van de tekst in ToPX niet matcht met de conventies (Publiek..., Intern...), dan wordt de letterlijke waarde uit ToPX overgenomen. In alle gevallen wordt de ToPX-waarde omgezet naar onderkast, behalve de naam van de zorgdrager. Die blijft zoals in de settings ingesteld.
- Anders, als er zich in ToPX _geen_ element `<omschrijvingBeperkingen>` bevindt, of de tekst daarin is leeg, èn als er in de settings een waarde is ingevuld, dan wordt de waarde uit de settings gebruikt volgens dezelfde regels als bij  `<omschrijvingBeperkingen>` (zie hierboven).
- Anders: er wordt een waarschuwing naar de logfile geschreven en er wordt geen element `<SecurityTag>` geplaatst. Het effect is dat de toegang in Preservica uiteindelijk (via de SIP Creator) komt te staan op de waarde die aan de SIP Creator wordt meegegeven, en dat is uiteindelijk weer de waarde uit de settings, maar dan niet geconverteerd.

**Comment by pmasereeuw** [comment]
Ik vraag me af of het niet beter is om de default securitytag bij aanroep van de SIP Creator op "closed" te zetten. Daarmee voorkom je onbedoelde openbaarheid; de gedachte is immers dat de toegang netjes via de settings of de ToPX-files geregeld wordt. Het is hoe dan ook niet wenselijk dat de ongeconverteerde waarde uit de settings wordt overgenomen. En het doen van dezelfde omzetting in de SIP Creator als in de transform zou kunnen, maar vereist een centralisatie van de logica over twee XSLWeb-applicaties heen. Niet ondenkbaar, maar rommeling. @avbentem wat vind jij?

**Comment by pmasereeuw** [comment]
Oh - ik lees nog even terug naar een [comment](https://github.com/noord-hollandsarchief/preingest/issues/104#issuecomment-804903573) hierboven. Het is zelfs nog iets subtieler qua SIP Creator.

**Comment by pmasereeuw** [comment]
Misschien het beste om de SIP Creator als securitytag-parameter altijd "closed" mee te geven en de settings daar niet te gebruiken, en bij de transform ook `<SecurityTag>closed</SecurityTag>` te plaatsen als we door alle condities heen gevallen zijn.

**Comment by avbentem** [comment]
Ja, dat laatste lijkt mij prima.

**Comment by pmasereeuw** [comment]
@avbentem ik heb dit uitgevoerd: als er geen waarde in ToPX is, en ook niet in de settings, wordt een SecurityTag met waarde closed gegenereerd. Dit gaat goed.

Tevens geeft ik de SIP Creator de waarde closed mee voor de securitytag-parameter. Dat geeft een griezelig effect. De SIP Creator maakt namelijk twee `<Collection>`-elementen aan: de eerste voor de parent collection (indien opgegeven; in het voorbeeld is de id 123) en de tweede voor de nieuwe collectie. Zie het screenshot hieronder.

Probleem is dat de eerste `<Collection>` de waarde krijgt die op de command line aan de SIP Creator wordt meegegeven. Ik moet dus uitzoeken of het effect na ingest niet zal zijn dat de bestaande collectie onbedoeld niet meer toegankelijk is (en dat dat dan ook geldt voor alles eronder).

![image](https://user-images.githubusercontent.com/6839743/113293399-00534780-92f6-11eb-8ff6-a26a6f34411e.png)
