### ISSUE TITLE
Create overall report (Excel?)

### ISSUE THREAD

**Issue by avbentem** [noord-hollandsarchief/preingest#3]
PDF may be look better as an official document, but Excel would allow for editing and filtering.

**Comment by pmasereeuw** [comment]
@avbentem als ik het goed zie, is er geen tabblad waar in Excel verslag wordt gedaan van de topx2xip-transform. Ik kwam daar achter toen ik die wilde hergebruiken voor een nieuw tabblad voor de voorwas. Ik neem aan dat het een goed idee is om beide tabbladen toe te voegen?

**Comment by avbentem** [comment]
@pmasereeuw ja, inderdaad.

**Comment by pmasereeuw** [comment]
Done

**Comment by avbentem** [comment]
For future reference: the output also does not include the results of SIP Creator. That may not help a lot anyway as that would not be something to send to the archive's owner. But as errors are only captured in `sipresult.log` they cannot be accessed using the frontend or Docker logs right now. See also #69.
