### ISSUE TITLE
Geautoriseerde naam van de zorgdrager

### ISSUE THREAD

**Issue by pmasereeuw** [noord-hollandsarchief/preingest#60]
De transformatie van `<omschrijvingBeperkingen>` naar `<SecurityTag>` vereist in sommige gevallen de geautoriseerde naam van de zorgdragen. Waar halen we die vandaan? Opties zijn:
- het element `<naam>` in de metadata op archiefniveau
- een parameter in een settingsfiletje, al dan niet doorgegeven via een request-parameter

Voorkeur heeft de eerste optie (element naam), aannemend dat dat de juiste naam is.

**Comment by pmasereeuw** [comment]
Done, merged into main branch, see also #98

**Comment by avbentem** [comment]
As we're blocked when we don't have the proper ISIL-code, I'd recommend to not rely on ISIL-codes for our internal codes any longer. But that's for others to decide.
