### ISSUE TITLE
SIP Creator needs many more user defined parameters

### ISSUE THREAD

**Issue by avbentem** [noord-hollandsarchief/preingest#79]
For SIP Creator we need:

- Option to pass a reference to an existing collection. In the Settings this is currently called `preservicaTarget`. Maybe rename to `preservicaCollectionRef`?
- Option to pass a new collection name and code. (For the user/frontend: any rules for that code? Do code and/or name need to be unique?) The Settings don't this yet. Let's leave `description` as is, so maybe add `preservicaNewCollectionTitle` and `preservicaNewCollectionCode` or something less verbose?
- Option to pass value for `-status`, or can we always derive that from the first bullets above?
- Option to pass default security tag. In the settings this is currently called `preservicaSecurityTag` and is either `open` or `closed`.
- Option to pass value for `-ignoreparent`?
- Do we need `-singledu` for the Provinciale Bladen? 

See also [our own Excel sheet in SharePoint](https://noordhollandsarchief.sharepoint.com/:x:/r/sites/ImplementatiePreserveringsvoorziening/_layouts/15/Doc.aspx?sourcedoc=%7B9E29F946-E062-4D7D-B2D1-EFECA5F3525B%7D&file=CMD%20SIP%20creator%20settings.xlsx&action=default&mobileredirect=true).

https://developers.preservica.com/api-reference/sip-creator-command-line shows the following (and much more):

Option | Value | Description
-- | -- | --
-status | NEW (default) or SAME | If  NEW is specified, the SIP produced will be ingested into a new  collection using the values specified. If SAME is specified, the colref  parameter must be provide and the SIP produced will be ingested into the  collection specified by the colref parameter. If this collection cannot  be found the ingest will fail.
-coltitle |   | Title  of the collection to create. Ignored if the status is SAME and will  default to "collection" if not specified when the status is NEW.
-colcode |   | Code  of the collection to create. Ignored if the status is SAME and will  default to "code" if not specified when the status is NEW.
-colref |   | Unique  reference for the collection. Required if the status is SAME and must  correspond to a valid collection Reference within Preservica. Not  required if the status is NEW causing the reference to be automatically  generated but can be specified if required.

**Comment by pmasereeuw** [comment]
Voor de discussie over de securityTag zie ook onder #104

**Comment by pmasereeuw** [comment]
The fields `<CollectionCode>` and `<Title>` (on the archive level) are currently retrieved from ToPX (`<identificatieKenmerk>` and `<naam>`). The values from the settings (passed to the command line) have no effect when running the SIP Creator. If we want them to have effect, we need to delete the elements from the XIP XML (not just leave them empty).

As for the CollectionRef: the situation is more complicated and we couldn't figure out what the consequences are of all possible combinations of leaving the element out of the XIP or not in combination with passing it on the command line (also using -status new/same and the corresponding attribute in XML). In some cases, the SIP Creator creates two `<Collection>` elements, where the refs and parentrefs are placed in a way that we do not yet fully understand.

Currently (April 8, 2021) the idea is not to pass any of these values on the SIP Creator command line, but instead use the values that the topx2xip-conversion puts into the XIP. That seems to give an adequate and clear mode of operation.

**Comment by pmasereeuw** [comment]
**TODO**: testen met incrementele ingest, mogelijk in combinatie met -ignoreparent.
Arjan zegt:
Bij opslitsen in 3 jaartallen ook <identificatiekenmerk> in de .metadata op archiefniveau even aanpassen, zodat we kunnen zien of er gekke dingen gebeuren met de bestaande folder? En dan, bijvoorbeeld, 2015 ingesten als NEW en 2016 en 2017 als SAME met -ignoreparent (of een equivalent in XIP, als dat te vinden is)?

**Comment by avbentem** [comment]
If XIPv4 allows for setting some description for a collection, then it may be nice to copy that from the (optional) settings too. That makes it a bit easier to find new ingests, as we cannot control `<Title>` and `CollectionCode>`, which are copied from ToPX. (Assuming we didn't actually forget to copy some relevant description from ToPX; if ToPX offers something then that may be better than using the user input.)
