### ISSUE TITLE
GreenlistHandler should reject OLE2

### ISSUE THREAD

**Issue by avbentem** [noord-hollandsarchief/preingest#92]
`fmt/111` is not in [the greenlist](https://github.com/noord-hollandsarchief/preingest/blob/main/preingest/Noord.HollandsArchief.Pre.Ingest.WebApi/Datasource/greenlist.json), but is accepted anyway:

```json
{
  "sessionId": "e9ac917c-1875-bd9e-3281-021c2b444d19",
  "puid": "fmt/111",
  "name": "NL-HlmNHA_1212_6_Notulen bestuur gym 20071024.doc",
  "location": "/data/e9ac917c-1875-bd9e-3281-021c2b444d19/1212/1_Stukken_van_algemene_aard/Notulen/Bestuurs_en_commissievergaderingen/6/NL-HlmNHA_1212_6_Notulen bestuur gym 20071024.doc",
  "formatVersion": "",
  "formatName": "OLE2 Compound Document Format",
  "extension": "doc",
  "inGreenList": true
},
```

The same format is rejected for `Thumbs.db` files, like:

```json
{
  "sessionId": "e9ac917c-1875-bd9e-3281-021c2b444d19",
  "puid": "fmt/111",
  "name": "Thumbs.db",
  "location": "/data/e9ac917c-1875-bd9e-3281-021c2b444d19/1212/2_Stukken_betreffende_bijzondere_onderwerpen/PR/Clubblad/2003/34/Thumbs.db",
  "formatVersion": "",
  "formatName": "OLE2 Compound Document Format",
  "extension": "db",
  "inGreenList": false
},
```

DROID CSV export reports:

NAME | METHOD | STATUS | SIZE | TYPE | EXT | EXTENSION_MISMATCH | HASH | FORMAT_COUNT | PUID | MIME_TYPE | FORMAT_NAME | FORMAT_VERSION
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
NL-HlmNHA_1212_6_Notulen bestuur gym   20071024.doc | Signature | Done | 83968 | File | doc | FALSE |   | 1 | fmt/111 |   | OLE2 Compound Document Format |  
Thumbs.db | Signature | Done | 13312 | File | db | FALSE |   | 1 | fmt/111 |   | OLE2 Compound Document Format |  

**Maybe other formats are accepted erroneously as well?** So:

- Why is this accepted? (Do we need to revise the current approach?)

Files are part of the private archive for Concordia: [ole2-files-and-droid-report.zip](https://github.com/noord-hollandsarchief/preingest/files/6021095/ole2-files-and-droid-report.zip)

**Comment by mzeinstra** [comment]
Kan je verder specificeren wat je met afkeuren bedoelt? Stopt dan het ingest-proces? 

IMHO voegen we die objecten die geen Pronom ID toe aan een lijst met bestanden die voorgelegd moeten worden aan de zorgdrager.

**Comment by avbentem** [comment]
Een pre-ingest "action plan" (een of meer geselecteerde acties) stopt alleen als:

- Een actie echt mislukt (dan is er iets mis in de software/omgeving).
- Zodra het resultaat van de SIP Creator naar de Transfer Agent doorgezet zou worden **én** er dan in een of meer voorgaande stappen **in hetzelfde action plan** een of meer fouten gevonden zijn. Dus op dat moment moet besloten worden of de fouten wel of niet genegeerd mogen worden. Als de stap om de resultaten naar de Transfer Agent te kopiëren expliciet nog een keer uitgevoerd wordt, dan worden voorgaande fouten uit eerdere action plan(s) dus genegeerd.

En bovenstaande stappen 1 t/m 6 gelden dus per bestand. Ofwel, overal geldt: afkeuren/accepteren en verder met het volgende bestand. We willen immers altijd zo volledig mogelijk rapporteren.

**Comment by avbentem** [comment]
:warning: This comment is WORK IN PROGRESS; despite the bugs our approach needs some more discussion too.

I'm now seeing results like the following for the Concordia test set:

```json
{
  "location": "/data/e9ac917c-1875-bd9e-3281-021c2b444d19/1212/1_Stukken_van_algemene_aard/11/NL-HlmNHA_1212_11_Brief aan leden einde lessen 2009-12-12.doc",
  "name": "NL-HlmNHA_1212_11_Brief aan leden einde lessen 2009-12-12.doc",
  "extension": "doc",
  "formatName": "Microsoft Word Document",
  "formatVersion": "97-2003",
  "puid": "fmt/40",
  "isExtensionMismatch": "false",
  "message": "Extensie gevonden in NHA groene lijst maar wel met een andere Pronom ID. Droid Pronom = fmt/40, NHA groene lijst = fmt/ 40.",
  "inGreenList": true
},
```

Also, the troublesome bare OLE2 is still accepted:

```json
  "location": "/data/e9ac917c-1875-bd9e-3281-021c2b444d19/1212/1_Stukken_van_algemene_aard/Notulen/Bestuurs_en_commissievergaderingen/6/NL-HlmNHA_1212_6_Notulen bestuur gym 20071024.doc",
  "name": "NL-HlmNHA_1212_6_Notulen bestuur gym 20071024.doc",
  "extension": "doc",
  "formatName": "OLE2 Compound Document Format",
  "formatVersion": "",
  "puid": "fmt/111",
  "isExtensionMismatch": "false",
  "message": "Extensie gevonden in NHA groene lijst maar wel met een andere Pronom ID. Droid Pronom = fmt/111, NHA groene lijst = fmt/ 40.",
  "inGreenList": true
},
```

So:

- Apparently there's some excessive space in the greenlist for `fmt/ 40`:

    https://github.com/noord-hollandsarchief/preingest/blob/6decaac3c7fd55a103d20f7365793fb4b08e1bb8/preingest/Noord.HollandsArchief.Pre.Ingest.WebApi/Datasource/greenlist.json#L163-L169

- When there's no match, it should be rejected.

While fixing this, please also:

- Change `"isExtensionMismatch": "false"` to use a boolean
- Change `NHA groene lijst` into `voorkeurslijst` (it's unclear where the word "greenlist" originated from, but it has no meaning outside the pre-ingest software)

HOWEVER, for the OD NZKG testset, I also see, for example:

```json
{
  "location": "/data/30f4d73e-dc41-4473-9832-0bc58bc8259c/test-od-nzkg/Zaak 10025536/10025536 19305018 Zaak 10025536 - OLO-5690699 - Hans Rietveld Agrarisch Advies B.V. - Dorpsstraat 645 - Assendelft - het wijzigen van melk.pdf",
  "name": "10025536 19305018 Zaak 10025536 - OLO-5690699 - Hans Rietveld Agrarisch Advies B.V. - Dorpsstraat 645 - Assendelft - het wijzigen van melk.pdf",
  "extension": "pdf",
  "formatName": "Acrobat PDF/A - Portable Document Format",
  "formatVersion": "2u",
  "puid": "fmt/478",
  "isExtensionMismatch": "false",
  "message": "Extensie gevonden in NHA groene lijst maar wel met een andere Pronom ID. Droid Pronom = fmt/478, NHA groene lijst = fmt/95.",
  "inGreenList": true
},
...
{
  "location": "/data/30f4d73e-dc41-4473-9832-0bc58bc8259c/test-od-nzkg/Zaak 9959111/9959111 19040328 Aanvraagdocument.pdf",
  "name": "9959111 19040328 Aanvraagdocument.pdf",
  "extension": "pdf",
  "formatName": "Acrobat PDF/A - Portable Document Format",
  "formatVersion": "1b",
  "puid": "fmt/354",
  "isExtensionMismatch": "false",
  "message": "Extensie gevonden in NHA groene lijst maar wel met een andere Pronom ID. Droid Pronom = fmt/354, NHA groene lijst = fmt/95.",
  "inGreenList": true
},
...
{
  "location": "/data/30f4d73e-dc41-4473-9832-0bc58bc8259c/test-od-nzkg/Zaak 9990990/9990990 19293221 Tekening.pdf",
  "name": "9990990 19293221 Tekening.pdf",
  "extension": "pdf",
  "formatName": "Acrobat PDF 1.4 - Portable Document Format",
  "formatVersion": "1.4",
  "puid": "fmt/18",
  "isExtensionMismatch": "false",
  "message": "Extensie gevonden in NHA groene lijst maar wel met een andere Pronom ID. Droid Pronom = fmt/18, NHA groene lijst = fmt/95.",
  "inGreenList": true
},
...
{
  "location": "/data/30f4d73e-dc41-4473-9832-0bc58bc8259c/test-od-nzkg/Zaak 9992516/9992516 19135993 Statische berekening.pdf",
  "name": "9992516 19135993 Statische berekening.pdf",
  "extension": "pdf",
  "formatName": "Acrobat PDF 1.5 - Portable Document Format",
  "formatVersion": "1.5",
  "puid": "fmt/19",
  "isExtensionMismatch": "false",
  "message": "Extensie gevonden in NHA groene lijst maar wel met een andere Pronom ID. Droid Pronom = fmt/19, NHA groene lijst = fmt/95.",
  "inGreenList": true
},
```

So, our list seems very much incomplete and needs more discussion.

**Comment by avbentem** [comment]
After some more discussion: indeed, things like fmt/111 (bare OLE2) and fmt/18, fmt/19, fmt/354 and fmt/478 (PDF) which are not known in our list but for which we do know other id(s) in our list, need to be rejected. In other words, those should fall into step 6 like described above:

> 5. Indien Pronom id niet in onze lijst, maar de extensie wel, **én onze lijst heeft geen enkele Pronom id voor die betreffende extensie**: accepteren, klaar
> 6. Anders: afkeuren

**Comment by avbentem** [comment]
I just noticed that `"isExtensionMismatch": "true"` was missing in case of a mismatch, in pre-yesterday's version:

```json
{
  "location": "/data/30f4d73e-dc41-4473-9832-0bc58bc8259c/test-od-nzkg/Zaak 9992516/9992516 19427558 bouwkosten check.pdf",
  "name": "9992516 19427558 bouwkosten check.pdf",
  "extension": "pdf",
  "formatName": "Microsoft Excel Template",
  "formatVersion": "2007 onwards",
  "puid": "fmt/598",
  "message": "Verkeerde extensie combinatie gevonden.",
  "inGreenList": false
},
```

Now, after this has been made a boolean in https://github.com/noord-hollandsarchief/preingest/commit/ca3f97c558fdd02f4e8f1cc1270cb1b02a0ff9cf, we get `"isExtensionMismatch": false` instead of `true` for the very same erroneous document in the OD-NZKG test set:

```json
{
  "location": "/data/44bfa464-7fda-9684-1e26-be09d1dea341/test-od-nzkg/Zaak 9992516/9992516 19427558 bouwkosten check.pdf",
  "name": "9992516 19427558 bouwkosten check.pdf",
  "extension": "pdf",
  "formatName": "Microsoft Excel Template",
  "formatVersion": "2007 onwards",
  "puid": "fmt/598",
  "isExtensionMismatch": false,
  "message": "Verkeerde extensie combinatie gevonden.",
  "inGreenList": false
},
```

And after our call, same steps but with some examples:

1. Laat DROID de Pronom id bepalen (gebeurt al)
2. Indien geen id gevonden: afkeuren, klaar, volgende bestand
3. Indien DROID vindt dat de extensie niet klopt met de inhoud: afkeuren, klaar **(bijvoorbeeld `file.pdf` wat eigenlijk een Excelbestand is met fmt/598)**
4. Indien Pronom id in onze lijst: accepteren, klaar **(bijvoorbeeld `file.pdf` met fmt/95, fmt/276 of fmt/476; vanwege stap 3 weten we al dat de extensie ook klopt)**
5. Indien Pronom id niet in onze lijst, maar de extensie wel, **én onze lijst heeft geen enkele Pronom id voor die betreffende extensie**: accepteren, klaar **(bijvoorbeeld `file.wav`)**
6. Anders: afkeuren **(bijvoorbeeld `file.doc` met fmt/111, of `file.pdf` met fmt/18, fmt/19, fmt/354 of fmt/478)**
