### ISSUE TITLE
Extend Schematron validation to reject ToPX 'omschrijvingVoorwaarden' on file level

### ISSUE THREAD

**Issue by avbentem** [noord-hollandsarchief/preingest#98]
~ToPX allows for specifying the security tags of #60 at file level as well, but XIP v4/SIP Creator does not support that. As a temporary measure, we could validate/report if file-level tags are different than their parent's tags.~

ToPX allows for specifying the security tags of #60 at file level as well, but TMLO does not allow that, and Preservica XIP v4/SIP Creator does not support it. So, Schematron validation needs to be extended to reject any value in `<omschrijvingVoorwaarden>`.

**Comment by pmasereeuw** [comment]
As an addendum, the value of the omschrijvingBeperkingen element should comply with our conventions, see issue #60

**Comment by pmasereeuw** [comment]
Done, see also issue #60
