### ISSUE TITLE
Set up production instance for Transfer Agent

### ISSUE THREAD

**Issue by avbentem** [noord-hollandsarchief/preingest#99]
We never finished setting up/testing a second instance of the Transfer Agent. I think we got as far as:

- Run Client Installer 5.11
- Remove that one due to incomplete Java runtime
- Run Client Installer 5.10, yielding `C:\Preservica\Local\Transfer Agent` 
- Peek in the `installService.bat` batch file and think we can manage a 2nd instance

It seems an ActiveMQ broker is started as a dependency:

```
amq.broker.url=tcp://docker01:61612
```

This was referenced during installation as:

![image](https://user-images.githubusercontent.com/1497002/109810813-4c916600-7c2a-11eb-8afa-c4da749e035b.png)

> The Progress Message port is network address that is used by the SIP Creator to monitor progress of uploads using the Transfer Agent. The default value of 61612 should be used unless it is already reserved for another system.

And:

![image](https://user-images.githubusercontent.com/1497002/109811096-b3168400-7c2a-11eb-80ac-11018368c9b2.png)

So, it seems we can just define a random port (and have that ActiveMQ service running without ever being used).

If this does not work we'll need to look at https://github.com/noord-hollandsarchief/preingest/issues/52#issuecomment-766781434.

For testing, we can make this extra instance also use the Preservica test environment; we may need to figure out how we can tell which credentials were used.

If all works fine then also change the `uninstallService.bat` scripts and all, and maybe rename those to make things very clear. Also, repeat for the first instance to make that use "Test" in its names?

This also needs to be added to `"\\file02\PreNAS\Digitaal Atelier\07_Preingest\doc\docker01-setup-notes.rtf"`.

In [the README](../blob/main/README.md) I already boldly documented:

> To support both test and production environments, this needs to be running twice:
> 
> - :warning: this is yet untested.
> 
> - Install it using the Client Installer 5.10 wizard. You'll need a URL like `https://eu.preservica.com/sdb` and can
>   likely ignore a warning saying _"Connection to Preservica has been re-directed. Please check the URL and re-try.
>   This often happens if http is used instead of https"_.
>   
> - After installing it once, duplicate the result folder in `C:\Preservica\Local\Transfer Agent` to, say,
>   `C:\Preservica\Local\Transfer Agent Production`.
>   
> - In the copy, adjust the configuration file `C:\Preservica\Local\Transfer Agent Production\conf\upload.properties`,
>   to use a different upload folder (make sure it exists), use different credentials, and make the ActiveMQ broker use
>   another dummy port (this is used by SIP Creator GUI to monitor progress of uploads, but is not used in our case):
> 
>   ```text
>   upload.root=C:/Preservica/Local/UploadArea-Production
>   ...
>   preservica.username=prod-user@example.com
>   preservica.password=prod-password
>   preservica.url=https://eu.preservica.com/sdb
>   ...
>   amq.broker.url=tcp://docker01:61613
>   ```
> 
> - In the copy, adjust `installService.bat` and run that file to use different names, like:
> 
>   ```text
>   set SERVICE_NAME=TransferAgentProduction
>   set PR_DISPLAYNAME=Preservica Transfer Agent Production
>   ```

**Comment by pmasereeuw** [comment]
Ik heb de volgende acties uitgevoerd:
- De softwarefolder `Transfer Agent` hernoemd en gekopieerd, zodat er nu twee folders zijn: `Transfer Agent - Production` en `Transfer Agent - Test`. De oude folder bestaat nog onder de naam `Transfer Agent.bak`
- De verschillende batchfiles in de betreffende folder hernoemd naar een naam eindigend op `Prod` en `Test`. De batchfiles aangepast zodat er nu twee services draaien: `Preservica Transfer Agent Production` en `Preservica Transfer Agent Test`
- In de subfolder `conf/upload.properties` in beide gevallen het pad naar de upload-folder (property `upload.root`) aangepast, zie hieronder.
- In dezelfde propertiesfile, maar alleen voor productie, een poortnummer gewijzigd: `amq.broker.url=tcp://docker01:61613`. De testversie draait op de default poort `61612`. @avbentem vermoedt dat dit poortnummer alleen van belang is voor de progress rapportage van de GUI van de SIP Creator (we hebben tot nu toe de SIP Creator GUI niet opgedeeld in test en productie)
- Tevens de folder `UploadArea` opgedeeld in `UploadAreaProd` en `UploadAreaTest`. De originele folder bestaat nog onder de naam `UploadArea.bak`
- Tot slot is in de folder `C:\preingest` de `.env`-file aangepast, zodat de preingest-docker (container `Noord.HollandsArchief.Pre.Ingest.WebApi`) wijst naar de nieuwe UploadArea-folders.
